name: Deploy to EC2

on: 
  push:
    branches:
      - prd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh
            nvm use 20
            
            cd ~/frontend

            echo "Create .env file"

            cat <<EOF > .env
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_GOOGLE_OAUTH_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_GOOGLE_OAUTH_REDIRECT_URI }}
            NEXT_PUBLIC_GOOGLE_OAUTH_REDIRECT_URI_TEST=${{ secrets.NEXT_PUBLIC_GOOGLE_OAUTH_REDIRECT_URI_TEST }}
            NEXT_PUBLIC_KAKAO_MAP_JAVASCRIPT_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_MAP_JAVASCRIPT_KEY }}
            NEXT_PUBLIC_KAKAO_MAP_JAVASCRIPT_KEY_TEST=${{ secrets.NEXT_PUBLIC_KAKAO_MAP_JAVASCRIPT_KEY_TEST }}
            NEXT_PUBLIC_KAKAO_OAUTH_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_KAKAO_OAUTH_REDIRECT_URI }}
            NEXT_PUBLIC_KAKAO_OAUTH_REDIRECT_URI_TEST=${{ secrets.NEXT_PUBLIC_KAKAO_OAUTH_REDIRECT_URI_TEST }}
            NEXT_PUBLIC_KAKAO_REST_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_REST_API_KEY }}
            NEXT_PUBLIC_KAKAO_REST_API_KEY_TEST=${{ secrets.NEXT_PUBLIC_KAKAO_REST_API_KEY_TEST }}
            NEXT_PUBLIC_NAVER_OAUTH_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_NAVER_OAUTH_REDIRECT_URI }}
            NEXT_PUBLIC_NAVER_OAUTH_REDIRECT_URI_TEST=${{ secrets.NEXT_PUBLIC_NAVER_OAUTH_REDIRECT_URI_TEST }}
            NEXT_PUBLIC_TEST_API_URL=${{ secrets.NEXT_PUBLIC_TEST_API_URL }}
            EOF

            echo "pull latest code"
            git pull origin prd

            echo "install dependencies"
            npm install

            echo "Build"
            npm run build

            echo "Reload server"
            pm2 reload dshelper || pm2 start dshelper
